spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
    jmx:
      unique-names: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: SoundMentor-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sound_mentor
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
  mail:
    host: smtp.qq.com
    username: 291396312@qq.com
    password: avsbuhivzmrzcbde
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


organization:
  # 创建组织时默认最大用户容量
  defaultOrganizationCapacity: 999
  # 用户最多加入组织数量
  MaxOrganizations: 10

user:
  # 用户最大声音样本库数量限制
  maxSound: 100

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    img: img
    mp3: mp3
    doc: doc
    ppt: ppt

# 阿里云通义千问大模型配置
dashscope:
  api-key: sk-835ae53dacb948d1a49a4e8edf098f40
